[package]
name = "secret-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
graph-rs-sdk = "=3.0.1"
tokio = { version = "1.25.0", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures = "0.3"
dotenv = "0.15.0"

